CREATE TABLE CLIENTE(
	CPF INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	RUA VARCHAR(50),
	NUMERO INTEGER,
	BAIRRO VARCHAR (30)
)
SELECT * FROM cliente;
ALTER TABLE cliente ADD PRIMARY KEY(cpf);
ALTER TABLE cliente ADD CONSTRAINT PK_CPF PRIMARY KEY(cpf);
DROP TABLE cliente;

CREATE TABLE DEPARTAMENTO(
COD_DEP INTEGER NOT NULL,
NOME VARCHAR(50),
CONSTRAINT PK_COD_DEP PRIMARY KEY(COD_DEP)
);
CREATE TABLE FUNCIONARIO(
CPF INTEGER NOT NULL,
NOME VARCHAR(50),
CIDADE VARCHAR(50),
COD_DEP INTEGER,
CONSTRAINT PK_CPF_FUNC PRIMARY KEY (CPF),
CONSTRAINT FK_COD_DEP FOREIGN KEY (COD_DEP)
REFERENCES DEPARTAMENTO (COD_DEP)
);
SELECT * FROM FUNCIONARIO;