CREATE TABLE CLIENTE(
	CPF INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	RUA VARCHAR(50),
	NUMERO INTEGER,
	BAIRRO VARCHAR (30)
)

SELECT * FROM CLIENTE

CREATE TABLE FUNCIONARIO(
	CPF INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	CARGO VARCHAR(50) NOT NULL,
	PROJETOS VARCHAR(50)
)

SELECT * FROM FUNCIONARIO