CREATE TABLE MEDICO (
    CRM VARCHAR(50) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(50),
    DATA_NASCIMENTO DATE,
    CONSTRAINT PK_MEDICO PRIMARY KEY (CRM)
);

CREATE TABLE PACIENTE (
    CPF VARCHAR(50) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(50),
    CONSTRAINT PK_PACIENTE PRIMARY KEY (CPF)
);

CREATE TABLE MEDICO_ESPECIALIDADE (
    CRM_MEDICO VARCHAR(50) NOT NULL,
    ESPECIALIDADE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_MEDICO_ESPECIALIDADE PRIMARY KEY (CRM_MEDICO, ESPECIALIDADE),
    CONSTRAINT FK_CRM_MEDICO_ESP FOREIGN KEY (CRM_MEDICO) 
	REFERENCES MEDICO (CRM)
);

CREATE TABLE MEDICO_TELEFONE (
    CRM_MEDICO VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_MEDICO_TELEFONE PRIMARY KEY (CRM_MEDICO, TELEFONE),
    CONSTRAINT FK_CRM_MEDICO_TEL FOREIGN KEY (CRM_MEDICO) 
	REFERENCES MEDICO (CRM)
);

CREATE TABLE PACIENTE_TELEFONE (
    CPF_PACIENTE VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_PACIENTE_TELEFONE PRIMARY KEY (CPF_PACIENTE, TELEFONE),
    CONSTRAINT FK_CPF_PACIENTE_TEL FOREIGN KEY (CPF_PACIENTE) 
	REFERENCES PACIENTE (CPF)
);

CREATE TABLE CONSULTA (
    CRM_MEDICO VARCHAR(50) NOT NULL,
    CPF_PACIENTE VARCHAR(50) NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    CONSTRAINT PK_CONSULTA PRIMARY KEY (CRM_MEDICO, CPF_PACIENTE, DATA_CONSULTA),
    CONSTRAINT FK_CRM_MEDICO FOREIGN KEY (CRM_MEDICO) 
	REFERENCES MEDICO (CRM),
    CONSTRAINT FK_CPF_PACIENTE FOREIGN KEY (CPF_PACIENTE) 
	REFERENCES PACIENTE (CPF)
);