CREATE TABLE FILME (
    COD_FILME INTEGER,
    NOME VARCHAR(50) NOT NULL,
    GENERO VARCHAR(50),
    DATA_LANCAMENTO DATE,
    CONSTRAINT PK_FILME PRIMARY KEY (COD_FILME)
);

CREATE TABLE ATOR (
    ID_ATOR INTEGER,
    NOME VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATE,
    CONSTRAINT PK_ATOR PRIMARY KEY (ID_ATOR)
);

CREATE TABLE EXEMPLAR (
    COD_FILME INTEGER NOT NULL,
    NRO_EXEMPLAR INTEGER NOT NULL,
    STATUS_EXEMPLAR VARCHAR(50) DEFAULT 'Disponível' NOT NULL,
    CONSTRAINT PK_EXEMPLAR PRIMARY KEY (COD_FILME, NRO_EXEMPLAR),
    CONSTRAINT FK_COD_FILME FOREIGN KEY (COD_FILME) 
	REFERENCES FILME (COD_FILME)
);

CREATE TABLE CLIENTE (
    COD_CLIENTE INTEGER,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO_RUA VARCHAR(50),
    ENDERECO_NUMERO VARCHAR(50),
    ENDERECO_CIDADE VARCHAR(50),
    ENDERECO_CEP CHAR(50),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE FILME_ATOR (
    COD_FILME INTEGER NOT NULL,
    ID_ATOR INTEGER NOT NULL,
    CONSTRAINT PK_FILME_ATOR PRIMARY KEY (COD_FILME, ID_ATOR),
    CONSTRAINT FK_COD_FILME_ATOR FOREIGN KEY (COD_FILME) 
	REFERENCES FILME (COD_FILME),
    CONSTRAINT FK_ID_ATOR_FILME FOREIGN KEY (ID_ATOR) 
	REFERENCES ATOR (ID_ATOR)
);

CREATE TABLE ALUGUEL (
    COD_CLIENTE INTEGER NOT NULL,
    COD_FILME INTEGER NOT NULL,
    NRO_EXEMPLAR INTEGER NOT NULL,
    DATA_ALUGUEL DATE,
    DATA_DEVOLUCAO DATE,
    CONSTRAINT PK_ALUGUEL PRIMARY KEY (COD_CLIENTE, COD_FILME, NRO_EXEMPLAR, DATA_ALUGUEL),
    CONSTRAINT FK_COD_CLIENTE FOREIGN KEY (COD_CLIENTE) 
	REFERENCES CLIENTE (COD_CLIENTE),
    CONSTRAINT FK_EXEMPLAR_ALUGADO FOREIGN KEY (COD_FILME, NRO_EXEMPLAR) 
	REFERENCES EXEMPLAR (COD_FILME, NRO_EXEMPLAR)
);

CREATE TABLE CLIENTE_TELEFONE (
    COD_CLIENTE INTEGER NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CLIENTE_TELEFONE PRIMARY KEY (COD_CLIENTE, TELEFONE),
    CONSTRAINT FK_COD_CLIENTE_TELEFONE FOREIGN KEY (COD_CLIENTE) 
	REFERENCES CLIENTE (COD_CLIENTE)
);