CREATE TABLE Professor (
    PRONTUARIO_PROF VARCHAR(50) NOT NULL,
    NOME VARCHAR(50),
    PNOME VARCHAR(50),
    SNOME VARCHAR(50),
    DTANASC DATE,
    CONSTRAINT PK_PRONTUARIO_PROF PRIMARY KEY (PRONTUARIO_PROF)
);

CREATE TABLE Curso (
    ID_CURSO INTEGER NOT NULL,
    NOME_CURSO VARCHAR(50),
    NRO_SEMESTRES INTEGER,
    DTA_FUNDACAO DATE,
    CONSTRAINT PK_ID_CURSO PRIMARY KEY (ID_CURSO)
);

CREATE TABLE Aluno (
    PRONTUARIO_ALUNO VARCHAR(50) NOT NULL,
    NOME VARCHAR(50),
    PNOME VARCHAR(50),
    SNOME VARCHAR(50),
    DTA_NASC DATE,
    SEXO VARCHAR(10),
    ID_CURSO INTEGER,
    CONSTRAINT PK_PRONTUARIO_ALUNO PRIMARY KEY (PRONTUARIO_ALUNO),
    CONSTRAINT FK_ALUNO_CURSO FOREIGN KEY (ID_CURSO)
    REFERENCES CURSO(ID_CURSO)
);

CREATE TABLE Leciona (
    PRONTUARIO_PROF VARCHAR(50) NOT NULL,
    PRONTUARIO_ALUNO VARCHAR(50) NOT NULL,
    ANO INTEGER NOT NULL,
    SEMESTRE INTEGER NOT NULL,
    NOTA DOUBLE PRECISION,
    CONSTRAINT PK_LECIONA PRIMARY KEY (PRONTUARIO_PROF, PRONTUARIO_ALUNO, ANO, SEMESTRE),
    CONSTRAINT FK_LECIONA_PROF FOREIGN KEY (PRONTUARIO_PROF)
    	REFERENCES Professor(PRONTUARIO_PROF),
    CONSTRAINT FK_LECIONA_ALUNO FOREIGN KEY (PRONTUARIO_ALUNO)
    	REFERENCES Aluno(PRONTUARIO_ALUNO)
);
